services:
  graphdb:
    image: ontotext/graphdb:10.8.0
    restart: always
    hostname: graphdb
    ports:
      - 127.0.0.1:7200:7200
    volumes:
      - cbgp-graphdb:/opt/graphdb/home
    networks:
      - cbgp-default

  cbgp-databases:
    image: markw/cbgp-databases:0.6.0
    restart: always
    hostname: databases
    environment:
      - GRAPHDB_HOST=graphdb:7200
      - GRAPHDB_USER=cbgp
      - GRAPHDB_PASS=cbgp
      - CBGP_KB=https://w3id.org/CBGP-App#"
    ports:
      - 127.0.0.1:8000:4567
    networks:
      - cbgp-default

      
volumes:
  cbgp-graphdb:
    external: true

networks:
  cbgp-default:
